FROM ubuntu

LABEL owner='elen_anahit'
LABEL description='Node-exporter Dockerfile'
LABEL version='v1'

WORKDIR /node-exporter

ENV OS=linux
ENV ARC=amd64

ENV NODE_VERSION=1.7.0
ENV NODE_PORT=9100


# RUN apt update && apt install -y wget

ADD  http://github.com/prometheus/node_exporter/releases/download/v${NODE_VERSION}/node_exporter-${NODE_VERSION}.${OS}-${ARC}.tar.gz ${PWD}

RUN  tar --strip-components=1 -xzf node_exporter-${NODE_VERSION}.${OS}-${ARC}.tar.gz

RUN  rm -rf /var/lib/apt/lists/*
RUN rm -fr node_exporter-${NODE_VERSION}.${OS}-${ARC}*

EXPOSE ${NODE_PORT}

CMD ["./node_exporter", "--web.listen-address=:${NODE_PORT}"]
